### ISSUE TITLE
A rare string parsing bug, or something else?

### ISSUE THREAD

**Issue by BellandBlackBird** [jdferreira/sleepyjson#1]
In a json file I have, the json object isn't malformed:
...text and more text", "sentence_index": 1,
is what is inside the file.
But I still get this traceback:
Traceback (most recent call last):
  File "/Users/alvbj/PycharmProjects/text-2-ssyk/src/sleepyjsontest.py", line 8, in <module>
    for counter, ad in enumerate(reader):
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 285, in __iter__
    yield from self.array_iter()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 297, in array_iter
    self.current_child = self.read_next_array_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 323, in read_next_array_child
    must_end = self.seek_next_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 384, in seek_next_child
    self.file.seek(self.current_child.end_position())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 239, in end_position
    self.seek_to_end()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 410, in seek_to_end
    for _ in self:
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 283, in __iter__
    yield from (key for key, _ in self.items())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 283, in <genexpr>
    yield from (key for key, _ in self.items())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 315, in items
    self.current_child = self.read_next_object_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 342, in read_next_object_child
    must_end = self.seek_next_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 384, in seek_next_child
    self.file.seek(self.current_child.end_position())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 239, in end_position
    self.seek_to_end()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 410, in seek_to_end
    for _ in self:
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 283, in __iter__
    yield from (key for key, _ in self.items())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 283, in <genexpr>
    yield from (key for key, _ in self.items())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 315, in items
    self.current_child = self.read_next_object_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 342, in read_next_object_child
    must_end = self.seek_next_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 384, in seek_next_child
    self.file.seek(self.current_child.end_position())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 239, in end_position
    self.seek_to_end()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 410, in seek_to_end
    for _ in self:
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 285, in __iter__
    yield from self.array_iter()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 297, in array_iter
    self.current_child = self.read_next_array_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 323, in read_next_array_child
    must_end = self.seek_next_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 384, in seek_next_child
    self.file.seek(self.current_child.end_position())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 239, in end_position
    self.seek_to_end()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 410, in seek_to_end
    for _ in self:
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 283, in __iter__
    yield from (key for key, _ in self.items())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 283, in <genexpr>
    yield from (key for key, _ in self.items())
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 315, in items
    self.current_child = self.read_next_object_child()
  File "/Users/alvbj/opt/anaconda3/envs/text-2-ssyk/lib/python3.8/site-packages/sleepyjson/node.py", line 348, in read_next_object_child
    raise ValueError(
ValueError: Unexpected input 'sentence_i' inside object

It is as if it cannot detect the comma or the quote char, even though it has successfully parsed this string over 3000 times before in the json file. Can you help me with this? Your project is very useful to me....

**Comment by jdferreira** [comment]
Hi!

I'l try to take a look at it over the weekend.

I suspect I know what may be happening, but to confirm, can you check what happens if you change the JSON file so that particular string "sentence_index" becomes "sentence_xxxxx", please?

**Comment by jdferreira** [comment]
On second thought, it might be something other than what I was thinking.

Would you be willing to share the JSON file?

**Comment by BellandBlackBird** [comment]
Sure!
[test.json.zip](https://github.com/jdferreira/sleepyjson/files/6220490/test.json.zip)
I instead get the error:
"ValueError: Unexpected input 'sentence_x' inside object"
But I have observed that, new errors pop up if I remove that key/value pair, other pairs are found to be in error.

**Comment by jdferreira** [comment]
I've just uploaded a correction. The code now correctly handles your file.

The problem was that, because I don't want to read the whole file into memory at once, I read strings in chunks, and was incorrectly detecting whether a quote character was part of the string or marked the end of the string.

In your case, you had a such an unlucky string which aligned perfectly with the buffer so that down the line, the buffer started at a termination quote character and ended in a backslash, which the parser was interpreting as the quote being escaped.

If you update through `pip` you should get the correct code now.

Thank you for taking the time to report the bug and to help solve it :)

**Comment by BellandBlackBird** [comment]
You are a champion Mr. Ferreira! Thank you for helping Swedish society by helping me and Jobtech run through loads of data on my shitty computer.

Från: "João D. Ferreira" ***@***.***>
Svara till: jdferreira/sleepyjson ***@***.***>
Datum: måndag 29 mars 2021 17:25
Till: jdferreira/sleepyjson ***@***.***>
Kopia: Björn Alvinge ***@***.***>, Author ***@***.***>
Ämne: Re: [jdferreira/sleepyjson] A rare string parsing bug, or something else? (#1)


Closed #1<https://github.com/jdferreira/sleepyjson/issues/1>.
